controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    ptz_camera_controller:
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
  ros__parameters:
    joints:
      - fl_steering_wheel
      - fr_steering_wheel
      - rl_steering_wheel
      - rr_steering_wheel
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    joints:
      - fl_wheel
      - fr_wheel
      - rl_wheel
      - rr_wheel
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

ptz_camera_controller:
  ros__parameters:
    joints:
      - ranger_mini_camera_pan_joint
      - ranger_mini_camera_tilt_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      ranger_mini_camera_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
      ranger_mini_camera_tilt_joint: {p: 100.0, i: 0.01, d: 10.0}